package com.pomodoro;

public interface IWritingService {

    String NEW_LINE = "\n";
    String WELCOME = "WELCOME ";
    String GOOD_BYE = "GOODBYE! ";
    String CREATE = "CREATE ";
    String CREATED = "CREATED ";
    String CREATING = "CREATING ";
    String CONTINUE = "CONTINUE ";
    String DELETE = "DELETE ";
    String ACCOUNT = "ACCOUNT ";
    String PASSWORD = "PASSWORD ";
    String SESSIONs = "SESSION(S) ";
    String LOGGED = "LOGGED ";
    String DELETED = "DELETED ";
    String ANYTHING = "ANYTHING ";
    String START = "START ";
    String STOP = "STOP ";
    String COUNT = "COUNT ";
    String WORK = "WORK ";
    String TIME = "TIME ";
    String BREAK = "BREAK ";
    String PLEASE = "PLEASE ";
    String USE = "USE ";
    String WITHOUT = "WITHOUT ";
    String CHECK = "CHECK ";
    String STATISTICS = "STATISTICS ";
    String REPEAT = "REPEAT ";
    String OLD = "OLD ";
    String AND = "AND ";
    String DEFAULT = "DEFAULT ";
    String SETTINGS = "SETTINGS ";
    String OWN = "OWN ";
    String AGAIN = "AGAIN ";
    String ALREADY = "ALREADY ";
    String EXISTS = "EXISTS ";
    String ACTIVITY = "ACTIVITY ";
    String FROM = "FROM ";
    String EXISTING = "EXISTING ";
    String DO = "DO ";
    String AS = "AS ";
    String A = "A ";
    String AN = "AN ";
    String THE = "THE ";
    String IN = "IN ";
    String TO = "TO ";
    String OR = "OR ";
    String YES = "YES ";
    String NO = "NO ";
    String DOES = "DOES ";
    String NOT = "NOT ";
    String EXIST = "EXIST ";
    String WRONG = "WRONG ";
    String ABOUT = "ABOUT ";
    String GUEST = "GUEST ";
    String N_EW = "NEW ";
    String CHOOSE = "CHOOSE ";
    String SHORT = "SHORT ";
    String LONG = "LONG ";
    String WANT = "WANT ";
    String CHOICE = "CHOICE ";
    String TYPE = "TYPE ";
    String USER = "USER ";
    String YOUR = "YOUR ";
    String YOU = "YOU ";
    String NAME = "NAME ";
    String APP = "APP ";
    String POMODORO = "POMODORO ";
    String DURATION = "DURATION ";
    String INFO = "INFO ";
    String EXIT = "EXIT ";
    String SAVE = "SAVE ";
    String DATA = "DATA ";
    String PREVIOUS = "PREVIOUS ";
    String NEXT = "NEXT ";
    String ONE = "(1). ";
    String TWO = "(2). ";
    String THREE = "(3). ";
    String FOUR = "(4). ";
    String FIVE = "(5). ";
    String SIX = "(6). ";
    String SEVEN = "(7). ";
    String EIGHT = "(8). ";
    String NINE = "(9). ";
    String TEN = "(10). ";

    void helloMessageMenu();
    void helloMessageUserMenu(String userName);
    String typeUserName();
    String typePassword();
    int typeChoiceNumber();
    String typeChoiceText();

}
